# Configuración de servidor
server:
  port: 8080
  servlet:
    context-path: /api

# Configuración de base de datos
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuración de Swagger con Springdoc
springdoc:
  api-docs:
    path: /v3/api-docs # Ruta para obtener el JSON de OpenAPI
  swagger-ui:
    path: /swagger-ui.html # Ruta para la interfaz Swagger
